# Generated by Django 4.1 on 2022-08-25 01:43

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', null=True, use_pytz=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', null=True, use_pytz=True),
        ),
    ]
