# Generated by Django 4.1 on 2022-08-25 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('i', 'Clock In'), ('o', 'Clock Out'), ('b', 'Begin Break'), ('e', 'End Break')], default='w', help_text='Pay period type', max_length=1)),
                ('action_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
